/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package School_Batting;

/**
 *
 * @author Jcj
 */
public class StartScreen extends javax.swing.JFrame
{

    /**
     * Creates new form StartScreen
     */
    public StartScreen()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        headerPanel = new javax.swing.JPanel();
        exit_Button1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        login_Panel = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerPanel.setBackground(new java.awt.Color(255, 255, 255));
        headerPanel.setName(""); // NOI18N
        headerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit_Button1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        exit_Button1.setText("X");
        exit_Button1.setBorderPainted(false);
        exit_Button1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit_Button1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        exit_Button1.setIconTextGap(0);
        exit_Button1.setOpaque(true);
        exit_Button1.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                exit_Button1MouseClicked(evt);
            }
        });
        exit_Button1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                exit_Button1ActionPerformed(evt);
            }
        });
        headerPanel.add(exit_Button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1890, 10, -1, -1));

        jLabel1.setBackground(headerPanel.getBackground());
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        headerPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 6, 462, 129));

        getContentPane().add(headerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, -1));

        login_Panel.setBackground(new java.awt.Color(255, 255, 255));
        login_Panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(44, 111, 198)));
        login_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setBackground(login_Panel.getBackground());
        jTextField1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTextField1ActionPerformed(evt);
            }
        });
        login_Panel.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 229, 430, 76));

        getContentPane().add(login_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 300, 720, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exit_Button1MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_exit_Button1MouseClicked
    {//GEN-HEADEREND:event_exit_Button1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_exit_Button1MouseClicked

    private void exit_Button1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_exit_Button1ActionPerformed
    {//GEN-HEADEREND:event_exit_Button1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exit_Button1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextField1ActionPerformed
    {//GEN-HEADEREND:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(StartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(StartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(StartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(StartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new StartScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exit_Button1;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel login_Panel;
    // End of variables declaration//GEN-END:variables
}
